# Generated by Django 2.2.12 on 2021-06-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('share', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
